### ISSUE TITLE
flipper tutorial  not working

### ISSUE THREAD

**Issue by Xib1uvXi** [substrate-developer-hub/substrate-contracts-workshop#65] opened 2020-05-19 06:54 UTC
i ran flipper totorial, flipper contract not working

create contract:

```bash
cargo contract new flipper

cd flipper

cargo contract build && cargo contract generate-metadata
```

start substrate node:

```bash
./target/release/substrate purge-chain --dev

./target/release/substrate --dev
```

use polkadot.js apps ui upload wasm success

use polkadot.js apps ui  deploy contract success

but, i call ``get()``,  no working

i found the rpc err :

```json
{"jsonrpc":"2.0","error":{"code":-32602,"message":"`100000000000` > u32::max_value(), the max block number is u32."},"id":92}
```

like this:

![call_get](https://raw.githubusercontent.com/Xib1uvXi/rust_by_example/master/call_contract_err.png)

so, i reset gas:

100000000000 ->  1000000000

get a new err 

```json
{"jsonrpc":"2.0","result":{"error":null},"id":130}
```

like this：

![call_get_err2](https://raw.githubusercontent.com/Xib1uvXi/rust_by_example/master/rpc_err2.png)

Any ideas?
Thanks

substrate version:

```bash
➜  substrate git:(7e9a2ae78) ./target/release/substrate --version        
substrate 2.0.0-alpha.8-7e9a2ae78-x86_64-macos
```

polkadot.js apps ui version:

```bash
apps v0.42.0-beta.142
```

cargo-contract version

``` bash
➜  flipper cargo contract --version
cargo-contract 0.6.1
```

**Comment by Stefie** [comment] 2020-05-19 07:11
Hi @Xib1uvXi ,
unfortunately the the contracts RPC method implementation in the Apps UI is currently broken.
It is a known issue, see for example here https://github.com/polkadot-js/apps/pull/2743#issuecomment-628248018. It's also already being logged here https://github.com/substrate-developer-hub/tutorials/issues/39. 
We're working on fixing that!

**Comment by Xib1uvXi** [comment] 2020-05-19 07:23
Thank you for your reply

**Comment by Longfld** [comment] 2020-05-19 08:12
the same issue for me, glad you are aware of it

**Comment by anuragjha** [comment] 2020-06-06 02:47
Yeah facing the empty get call issue. Is there anyway to build around it. I really have to finish a smart contract application. Should I use evm-contract pallet instead ?

**Comment by Robbepop** [comment] 2020-06-06 09:57
The problems are caused by the current Polkadot JS Apps implementation not being up to date and not with the underlying pallet or smart contract language. We are working on a fix for the problems and will asap push an update.

**Comment by yangwao** [comment] 2020-10-06 13:36
ink1 and substrate 2.0.0rc4 worked for me, but that not the ultimate solution. Wait for ink3.0 and Substrate 2.0 and Apps will reflect this change in @polkadot/api pretty anytime I guess.

**Comment by riusricardo** [comment] 2020-10-14 20:07
Closing because the tutorial has been updated.

**Closed by riusricardo** 2020-10-14 20:07 UTC
